export enum ItemFilterIconColor {
    None = 0,
    White = 1,
    LightYellow = 2,
    Beige = 3,
    LightOrange = 4,
    LightRed = 5,
    LightPink = 6,
    LightPurple = 7,
    LightBlue = 8,
    LightAqua = 9,
    Green = 10,
    Yellow = 11,
    Orange = 12,
    Red = 13,
    Pink = 14,
    Purple = 15,
    Blue = 16,
    Aqua = 17,
}