export enum ItemFilterIcon {
    None = 0,
    Acolyte = 1,
    Mage = 2,
    Primalist = 3,
    Rogue = 4,
    Sentinel = 5,
    Sword = 6,
    Axe = 7,
    Amulet = 8,
    BodyArmor = 9,
    Belt = 10,
    Boots = 11,
    Gloves = 12,
    Helmet = 13,
    Relic = 14,
    Ring = 15,
    Shield = 16,
    Rune = 17,
    Square = 18,
    Triangle = 19,
    Idols = 20,
    Forge = 21,
    Key = 22,
    Star = 23,
}