export enum LevelConditionType {
    BELOW_LEVEL = "BELOW_LEVEL",
    ABOVE_LEVEL = "ABOVE_LEVEL",
    MAX_LVL_BELOW_CHARACTER_LEVEL = "MAX_LVL_BELOW_CHARACTER_LEVEL",
    HIGHEST_USABLE_LEVEL = "HIGHEST_USABLE_LEVEL"
}